{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n>        assert False\nE        assert False\n\ntest_file13.py:7: AssertionError"}, "start": 1614247805475, "stop": 1614247805475, "uuid": "e47eebda-c49a-4fef-bfeb-0d362a94ec52", "historyId": "1ecf0c7c5f1e46a41cfa32fb7ddd0a21", "testCaseId": "861c02ea26fe3c3a4fc1a48d20e8b399", "fullName": "test_file13#test_failure", "labels": [{"name": "suite", "value": "test_file13"}, {"name": "host", "value": "ZhouKun-Laptop"}, {"name": "thread", "value": "17572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_file13"}]}